### ISSUE TITLE
Make UDP packet size configurable

### ISSUE THREAD

**Issue by sklirg** [telenornms/skogul#148]
Hard-coding the UDP packet size to 9000 is not necessary. Interfaces might have bigger MTUs than that, for example loopback, which sports a massive 65k in linux.

https://github.com/telenornms/skogul/blob/v0.10.0/receiver/udp.go#L85

**Comment by moogacs** [comment]
I think I am gonna work on that one, it it's ok with you

**Comment by KristianLyng** [comment]
fixed by #155
