### ISSUE TITLE
JSON debug output should support not pretty-printing

### ISSUE THREAD

**Issue by sklirg** [telenornms/skogul#154]
We've seen a lot of use cases where the debug output is printed to stdout, which is actually systemd/journald, which rather poorly handles the pretty-printed JSON. If we support turning pretty printing off we could have the JSON printed on a single line, which works nicely in journald, and it can even be piped out as a full json structure on one line.

This also plays nice when logs are shipped off to log facilities.

Default should be to pretty print.

https://github.com/telenornms/skogul/blob/primary/sender/debug.go#L48

**Comment by KristianLyng** [comment]
Pretty sure I fixed this already with the json encoder. Yup.
