### ISSUE TITLE
MQTT receiver says ClientID is random, but it is empty string

### ISSUE THREAD

**Issue by sklirg** [telenornms/skogul#158]
https://github.com/telenornms/skogul/blob/primary/receiver/mqtt.go#L47

I think `skogul-<random>` would be a nice default, where random is some random string which gets randomised every time skogul starts the receiver.

**Comment by KristianLyng** [comment]
We spoke about the issue, but for the record, the intended behavior IS that clientid should be skogul-(random)-(random)

https://github.com/telenornms/skogul/blob/primary/internal/mqtt/mqtt.go#L114

The randomness could certainly be better, but that's a different issue.

We need to verify if this is an actual issue or not.

**Comment by sklirg** [comment]
It is random string. Well, `skogul-<random int>-<random int>`.
