### ISSUE TITLE
Number of threads for batch sender should be configurable

### ISSUE THREAD

**Issue by sklirg** [telenornms/skogul#172]
It is currently using runtime.numCPU(), which should be the default, but it should also be configurable.

https://github.com/telenornms/skogul/blob/v0.10.7/sender/batch.go#L92

**Comment by burntcarrot** [comment]
@sklirg Either we can pass the parameter to the `setup` function:
https://github.com/telenornms/skogul/blob/3f8a1714dd6d65b156faa0e27e440787e82bf541/sender/batch.go#L75

but, that would mean `Send` needs to be able to pass the parameter to `setup`, which I guess is not preferrable: 
https://github.com/telenornms/skogul/blob/3f8a1714dd6d65b156faa0e27e440787e82bf541/sender/batch.go#L175-L182

I instead think we should add `numThreads` to the `Batch` struct:
https://github.com/telenornms/skogul/blob/3f8a1714dd6d65b156faa0e27e440787e82bf541/sender/batch.go#L62

Which can then can be utilized by `setup()` effectively:

(before)
https://github.com/telenornms/skogul/blob/3f8a1714dd6d65b156faa0e27e440787e82bf541/sender/batch.go#L92-L96

(after)
```
bat.out = make(chan *skogul.Container, bat.numThreads)
	for i := 0; i < bat.numThreads; i++ {
		go bat.flusher()
	}
```

Am I right or am I suggesting a wrong fix?

**Comment by sklirg** [comment]
This sounds good to me 😄👍

Extending Batch, that is

**Comment by burntcarrot** [comment]
I will open a PR in a few days! 😄👍

**Comment by burntcarrot** [comment]
Apologies as I wasn't available for a few days. I just created a PR, requesting review.
