### ISSUE TITLE
How Do I Rename Metric Fields?

### ISSUE THREAD

**Issue by jjackson107** [telenornms/skogul#292]
I am using Skogul (latest version, 0.21.1) to intake and parse Juniper UDP streaming telemetry data. I have it flattened down according to the provided examples, but I want to rename the flattened fields to look prettier. For example, `optics_diag_stats__module_temp` would be called something like `module_temp` or `ingress_stats__if_octets` would be `in_octets`.

Looking over the man page, I see a way to rename metadata but not actual fields. What is the best way to do this using built-in transformers?

Thanks!

**Comment by KristianLyng** [comment]
Good question, I don't think we've gotten around to writing this yet.

I see we have a way to copy and rename if you move fields from data to metadata, but we should obviously let you rename them as well... 

Somewhat slow response here, but I'll see about fixing this now :D It should be pretty quick.
