### ISSUE TITLE
Use go:generate or similar to generate/update telemetry protobuf code

### ISSUE THREAD

**Issue by KristianLyng** [telenornms/skogul#34]
The gen/ code is generated with a protobuf compiler and Juniper Telemetry data. How this is done should be set up in 'go:generate' or similar so it can be reproduced/updated.

**Comment by sklirg** [comment]
Should the protobuf files be included in the repository as well? Where would we want them to live?

**Comment by sklirg** [comment]
Also: This would require any developer to have protoc on their PATH if they would want to run `go generate` (I can't remember if  this happens by default when you install the golang library, so it might be a non-issue).

`go build` and `go run` would be unaffected.

My point is that if you are doing work unrelated to the protobuf "stuff" you shouldn't need dependencies for that specific portion of the code.

**Comment by KristianLyng** [comment]
So we can't get around that developers wanting to regenerate the protobuf .go-files will need some tooling supported, but I agree that they shouldn't need it if they aren't updating code.

The merged "fix" requires a working environment too, e.g., having 'protoc' in the path. However, I figure that that's not an unreasonable requirement, as we also ship working, pre-generated files now, which I think we should keep doing.

I also included the original tar-ball in the repo.

As it stands now, I'm fairly happy, though we have two different means of doing the same thing now, so maybe the issue is more of making a decision now?

At the very least, I think we can bump it from a 0.2-issue to something else, since it is documented in-repo how to regenerate the code, even if the "documentation" isn't necessarily perfect.

**Comment by KristianLyng** [comment]
I'm closing this, since the core issue is resolved. Other improvements we want should be separate issues.
