### ISSUE TITLE
Write/re-write log receiver, using logrus 

### ISSUE THREAD

**Issue by KristianLyng** [telenornms/skogul#35]
We need better logging, and #30 introduces logrus.

The log receiver needs to be updated to handle this, and should:

1. Ensure the initial read-path is quick and non-blocking. It should just read the logs and place them on a buffered channel, then move on (or similar). Code should be able to log extensively without having to worry about log performance at all. If logrus can't satisfy this, we have a problem.

2. Extract fields into metadata to as great an extent as possible.

3. Leverage transformers for filtering, but a basic log-level filter is OK. Simplicity of configuration is key: People will expect the log receiver to support filtering on log levels, so even if you _can_ use a transformer to do that, it will be such a common use case that it should live in the receiver.

Note that this issue is NOT about introducing logrus in general, but just the logrus-capable receiver, so we can forward logs.

We also need to address suppressing log output to stdout. I don't have a clear picture of how we want to do that. But I'm thinking we want to be able to echo e.g. warnings and above to stdout, while sending everything (trace, info, debug, warn, etc) down to the handler. This will allow us to have extensive logs in a log system (splunk/database), while still getting sensible debug-output.

Logrus also makes it easier to avoid loops: We should probably set a metadatafield indicating that this has passed through the log receiver, so we don't end up in feedback loops if splunk is unresponsive. Not entirely sure how that will work, though.

**Comment by KristianLyng** [comment]
I'm pushing this to 0.3 because it's an order of magnitude bigger than the other 0.2 tasks left.

**Comment by sklirg** [comment]
Fixed in #77
