### ISSUE TITLE
Conditional transformation based on a field in the metadata

### ISSUE THREAD

**Issue by sklirg** [telenornms/skogul#50]
### Feature request

I propose being able to apply a transformer to an incoming metric based on a conditional, e.g. matching it against a metadata field (sensorName, systemId, ...).

### Rationale

It is possible to apply multiple transformers to the same incoming container/metric, e.g. to first split it and then flatten it.

All transformers are being tried before the container is handed over to the sender.

Currently, we have configured 10 transformers where approximately 3 transformers are run per metric (split, extract, flatten). The other ones silently fail, e.g. because the target field for extract or flatten doesn't exist. I think this is "abusing" the way transformers work.

I find two potential pain points of this. 

1) The configuration can be hard to maintain simply because of the number of transformers applied to the same handler.
2) A simple transformer might apply to multiple metrics which could end up transforming/mangling the metrics in some way the user doesn't want or expect it to do, and there is no way around this (it's nice that it _can_ happen for all of the metrics, e.g. extracting the interface name from the data set, but I think it should be possible to skip it as well)

Furthermore, I haven't really dug deep regarding this, but some of the transformers might run for a bit before they fail which could have an impact on performance. E.g. extracting nested json-objects by casting a metric into `map[string]interface{}` on multiple levels before it realises the field it actually wants to extract doesn't actually exist.

### Potential solution

This feature could be implemented in the transformers, but at that point you wouldn't really solve the maintenance of the configuration issue.

I think that extending the handlers with a configuration option for mapping a transformer to a conditional would be the way to go.

Potential configuration:

```json
{
  "receivers": {
    "udp": {
      "type": "udp",
      "address": "[::1]:1337",
      "handler": "next"
    }
  },
  
  "handlers": {
    "next": {
      "parser": "json",
      "transformers": [
        {
          "transformer": "interface_info",
          "when": "sensorName",
          "is": "junos_system_linecard_interface"
        }
      ]
    }
  },
  
  "transformers": {
    "interface_info": {
      "type": "split",
      "field": "if_name"
    }
  }
}
```

**Comment by KristianLyng** [comment]
I think you illustrate the problem well, and we need to address this.

My immediate thought is that this can already be done - as a transformer. E.g.:

```

{
 "handlers": {
   ...
   "transformers": [ "conditional","extractIfName" ]
  },
  "transformers": {
     "conditional": {
          "type": "conditional",
          "conditions": [{
                "transformer": "interfaces",
                "when": "sensorname",
                "is": "junos_system_linecard_interface"
           }]
       },
      "interfaces": {
          "type": "split",
          "field": "interfaceInfo"
       },
       "extractIfName": {
           "type": "metadata",
            "extractFromMetadata": ["ifName"]
        }
     }
}
```
(Ok, that's probably not syntactically accurate, but you get the idea).

The downside of this approach is that configuration is still a bit messy, but in the non-complicated configurations where there are no conditional transformers, the configuration is much cleaner.

It also allow us to better switch implementation on the conditional logic, since it will not be part of the core API. 

That said, I'm open for discussion....

**Comment by KristianLyng** [comment]
Since this needs a bit more work, I'm bumping this to 0.3 so we can finish up the release - it's in a pretty good state.
