### ISSUE TITLE
Update MQTT receiver/sender config

### ISSUE THREAD

**Issue by KristianLyng** [telenornms/skogul#85]
The MQTT receiver and sender was written pre-json-config, and is suffering because of it.

It needs to be updated. I suggest:

1. Remove all use of net/url
2. Use "broker": "ip:port" and "topic": "..." 
3. A minor refactor of internal/mqtt. 

The latter can be a separate task/issue, but is tightly coupled with the configuration. The main problem is that there's a lot of "module state" where there shouldn't be, which makes it difficult to follow. There's also a good bit of copying from the receiver/sender's struct to the internal/mqtt/ variant of more or less the same data. This should be reduced or removed if possible.

**Comment by sklirg** [comment]
Resolved in #86
